#!/usr/local/bin/python3
# arguments: -c

import subprocess as sp
sp.call("source .docs_env/bin/activate", shell=True)


import os
import sys
from rich import print

def run(sub):
    sp.call(f"python3 .pnpm/{sub}", shell=True)

final = "src/.build_assets/icons.json"
icons_dir = "src/icons"

package_manager = os.environ.get('docs_PKG') or "yarn"

if not os.path.isdir(".pnpm/icona"):
    icona_repo = "git@github.com:robo-monk/ICONA.git"
    sp.call(f"git clone {icona_repo} .pnpm/icona", shell=True)


# build icons
print(f" [bold] Bundling icons... [/bold]")

run(f"icona/icona {icons_dir}")
sp.call(f"mv {icons_dir}.json {final}", shell=True)
# subprocess.call(f"python .pnpm/icona/icona {icons_dir}", shell=True)

if len(sys.argv) > 1:
    package_manager = sys.argv[1]

print(f"\n\n[bold cyan] Bundling with package manager: {package_manager} [/bold cyan] \n\n")
# subprocess.call("python3 .pnpm/scripts/sass", shell=True)
run(f"scripts/sass")

sp.call(f"{package_manager} run build", shell=True)

