#!/usr/local/bin/python3
# arguments: -c
# from config import config
# sb.call("source .docs_env/bin/activate", shell=True)
from script import * 


print("configureation is", config)
print("params are", params())

def run(sub):
    sb.call(f"python3 .pnpm/{sub}", shell=True)

final = "src/.build_assets/icons.json"
icons_dir = "src/icons"

package_manager = pkg_manager

if not os.path.isdir(".pnpm/icona"):
    icona_repo = "git@github.com:robo-monk/ICONA.git"
    sb.call(f"git clone {icona_repo} .pnpm/icona", shell=True)


# build icons
print(f" [bold] Bundling icons... [/bold]")

run(f"icona/icona {icons_dir}")
sb.call(f"mv {icons_dir}.json {final}", shell=True)
# subprocess.call(f"python .pnpm/icona/icona {icons_dir}", shell=True)

print(f"\n\n[bold cyan] Bundling with package manager: {package_manager} [/bold cyan] \n\n")
# subprocess.call("python3 .pnpm/scripts/sass", shell=True)
run(f"scripts/sass")
sb.call(f"{package_manager} run build", shell=True)

