#!/usr/local/bin/python3
# arguments: -c

import subprocess as sp
# from config import config
# sp.call("source .docs_env/bin/activate", shell=True)

import os
import sys
from rich import print
import script
# from script import test
# from script import config, params, env, pkg_manager



# print("configureation is", config())
print('using', script.pkg_manager)
sp.call(f"{script.pkg_manager} run dev", shell=True)
# print("params are", params())
# print('environment is ', params('env') or "dev")
# env = params('env') or "dev"
# pkg_manager = params('use') or config('package_manager')
