#!/usr/local/bin/python3
pkg_name = "docs"
pkg_name_npm = "docs"

from script import *
import requests


def release():
    sb.call("npm publish", shell=True)

package_manager = os.environ.get(f"{pkg_name}_PKG") or "yarn"


if len(sys.argv) > 1:
    package_manager = sys.argv[1]


os.environ[f"{pkg_name}_ENV"] = 'production'
run('build')

# test
proc = sb.Popen("yarn test", stdout=sb.PIPE, shell=True)
streamdata = proc.communicate()[0]
if (proc.returncode == 0):
    print(f"\n\n[italic green] Tests passed!  [/italic green] \n\n")
else:
    print(f"\n\n[bold red] Tests failed!!!!  [/bold red] \n\n")


# set version
v = requests.get(f"https://registry.npmjs.org/{pkg_name_npm}").json()['dist-tags']['latest']
console.print(f": Latest version published on npm: {str(v)}", style="dim")

package = {}
with open('package.json', 'r') as f:
    package = json.load(f)


pv = package['version']

tag = "bold green" if str(v) == str(pv) else "bold yellow"
console.print(f": Current local version: {pv}", style=tag)

print(f"[bold]\n\n Input new version please: [/bold]")
new_version = input("⇝ ")

if len(new_version) ==  0:
    new_version = pv

print(f"[italic]  Confirm publish this as version: {new_version} ?")
if input(f"[y/n] ⇝ ") == 'y':
    package['version'] = new_version
    with open('package.json', 'w') as outfile:
        json.dump(package, outfile, indent=4)

    release()
    print("\n [bold green] Package published succesfully to the NPM repository.")
else:
    print('\n[bold red] Aborted')


