#!/usr/local/bin/python3

from script import *

from flask import Flask, render_template, send_file
app = Flask(__name__, template_folder="../../", static_folder="../../")

@app.route('/')
def index():
    return render('index')
          
@app.route("/<file>")
def render(file):
    if "favicon" in file: return "<>"
    return render_template(f"{file}.html")
          
@app.route("/docs/<a>")
@app.route("/docs/<a>/<b>")
@app.route("/docs/<a>/<b>/<c>")
def serve(**e):
    return send_file("../../docs/" + "/".join(e.values()))
          
global c
def run_app(port, attempts=10):
    global c
    if attempts <= 0: return print("Could not start server. Too many ports in use.")
    try:
        attempts -= 1
        app.run(debug=True, port=port)
    except:
        warn(f"port {port} already in use. Trying next...")
        port += 1
        run_app(port, attempts)

if __name__ == '__main__':
    c = spawn("Starting server...")
    run_app(3333)
    c.done()
