#!/usr/local/bin/python3

from flask import Flask, render_template, send_file
app = Flask(__name__, template_folder="../../", static_folder="../../")

@app.route('/')
def index():
    return render('index')
          
@app.route("/<file>")
def render(file):
    if "favicon" in file: return "<>"
    return render_template(f"{file}.html")
          
@app.route("/docs/<a>")
@app.route("/docs/<a>/<b>")
@app.route("/docs/<a>/<b>/<c>")
def serve(**e):
    return send_file("../../docs/" + "/".join(e.values()))
          
if __name__ == '__main__':
    app.run(debug=True)
